# Auto-generated by tools/generate_tables.py
# Conditionally includes subsystem sources based on build defines

if("$ENV{PIOENV}" STREQUAL "goblin_head")
    include(p32_goblin_head_sources.cmake OPTIONAL)
    set(P32_GENERATED_SOURCES ${P32_GOBLIN_HEAD_SOURCES})
    message(STATUS "Including goblin_head subsystem sources")
endif()

if("$ENV{PIOENV}" STREQUAL "goblin_torso")
    include(p32_goblin_torso_sources.cmake OPTIONAL)
    set(P32_GENERATED_SOURCES ${P32_GOBLIN_TORSO_SOURCES})
    message(STATUS "Including goblin_torso subsystem sources")
endif()
