# Auto-generated by tools/generate_tables.py for subsystem: goblin_head
set(P32_GOBLIN_HEAD_SOURCES
    src/subsystems/goblin_head/goblin_head_component_functions.cpp
    src/subsystems/goblin_head/goblin_head_dispatch_tables.cpp
    src/subsystems/goblin_head/goblin_head_main.cpp
)

set(P32_GOBLIN_HEAD_HEADERS
    include/subsystems/goblin_head/goblin_head_component_functions.hpp
    include/subsystems/goblin_head/goblin_head_dispatch_tables.hpp
    include/subsystems/goblin_head/goblin_head_main.hpp
)
