# Auto-generated by tools/generate_tables.py
set(P32_GENERATED_SOURCES
    src/subsystems/test_head/test_head_component_functions.cpp
    src/subsystems/test_head/test_head_dispatch_tables.cpp
    src/subsystems/test_head/test_head_main.cpp
)

set(P32_GENERATED_HEADERS
    include/subsystems/test_head/test_head_component_functions.hpp
    include/subsystems/test_head/test_head_dispatch_tables.hpp
    include/subsystems/test_head/test_head_main.hpp
)
