# Auto-generated by tools/generate_tables.py for subsystem: goblin_torso
set(P32_GOBLIN_TORSO_SOURCES
    src/subsystems/goblin_torso/goblin_torso_component_functions.cpp
    src/subsystems/goblin_torso/goblin_torso_dispatch_tables.cpp
    src/subsystems/goblin_torso/goblin_torso_main.cpp
)

set(P32_GOBLIN_TORSO_HEADERS
    include/subsystems/goblin_torso/goblin_torso_component_functions.hpp
    include/subsystems/goblin_torso/goblin_torso_dispatch_tables.hpp
    include/subsystems/goblin_torso/goblin_torso_main.hpp
)
