#ifndef GOBLIN_HEAD_COMPONENT_FUNCTIONS_HPP
#define GOBLIN_HEAD_COMPONENT_FUNCTIONS_HPP

#include <cstddef>
#include <cstdint>
#include "esp_err.h"
#include "shared/BalanceCompensation.hpp"
#include "shared/BehaviorControl.hpp"
#include "shared/CollisionAvoidance.hpp"
#include "shared/EmergencyCoordination.hpp"
#include "shared/Environment.hpp"
#include "shared/FrameProcessor.hpp"
#include "shared/ManipulationControl.hpp"
#include "shared/MicrophoneData.hpp"
#include "shared/Mood.hpp"
#include "shared/SensorFusion.hpp"
#include "shared/SysTest.hpp"

// Auto-generated by tools/generate_tables.py
// Subsystem: goblin_head
// Controller: ESP32_S3_R8N16

// Component definition sourced from config\components\creature_specific\goblin_left_ear.json
struct goblin_left_ear_config {
    const char* name = "goblin_left_ear";
    const char* type = "SCAFFOLDED";
    const char* relative_filename = "config/components/creature_specific/goblin_left_ear.json";
    const char* description = "Auto-generated component.";
};

// Component definition sourced from config\components\creature_specific\goblin_left_eye.json
struct goblin_left_eye_config {
    const char* name = "goblin_left_eye";
    const char* type = "SCAFFOLDED";
    const char* relative_filename = "config/components/creature_specific/goblin_left_eye.json";
    const char* description = "Auto-generated component.";
};

// Component definition sourced from config\components\creature_specific\goblin_mouth.json
struct goblin_mouth_config {
    const char* name = "goblin_mouth";
    const char* type = "SCAFFOLDED";
    const char* relative_filename = "config/components/creature_specific/goblin_mouth.json";
    const char* description = "Auto-generated component.";
};

// Component definition sourced from config\components\creature_specific\goblin_nose.json
struct goblin_nose_config {
    const char* name = "goblin_nose";
    const char* type = "SCAFFOLDED";
    const char* relative_filename = "config/components/creature_specific/goblin_nose.json";
    const char* description = "Auto-generated component.";
};

// Component definition sourced from config\components\creature_specific\goblin_right_ear.json
struct goblin_right_ear_config {
    const char* name = "goblin_right_ear";
    const char* type = "SCAFFOLDED";
    const char* relative_filename = "config/components/creature_specific/goblin_right_ear.json";
    const char* description = "Auto-generated component.";
};

// Component definition sourced from config\components\creature_specific\goblin_right_eye.json
struct goblin_right_eye_config {
    const char* name = "goblin_right_eye";
    const char* type = "SCAFFOLDED";
    const char* relative_filename = "config/components/creature_specific/goblin_right_eye.json";
    const char* description = "Auto-generated component.";
};

// Component definition sourced from config\components\creature_specific\goblin_speaker.json
struct goblin_speaker_config {
    const char* name = "goblin_speaker";
    const char* type = "SCAFFOLDED";
    const char* relative_filename = "config/components/creature_specific/goblin_speaker.json";
    const char* description = "Auto-generated component.";
};

// ---------------------------------------------------------------------------
// Function prototypes
// ---------------------------------------------------------------------------
esp_err_t goblin_left_ear_init(void);
void goblin_left_ear_act(void);
esp_err_t goblin_left_eye_init(void);
void goblin_left_eye_act(void);
esp_err_t goblin_mouth_init(void);
void goblin_mouth_act(void);
esp_err_t goblin_nose_init(void);
void goblin_nose_act(void);
esp_err_t goblin_right_ear_init(void);
void goblin_right_ear_act(void);
esp_err_t goblin_right_eye_init(void);
void goblin_right_eye_act(void);
esp_err_t goblin_speaker_init(void);
void goblin_speaker_act(void);

// Declarations from config\components\creature_specific\goblin_left_ear.hdr
// Auto-generated header for goblin_left_ear
#include <esp_err.h>

esp_err_t goblin_left_ear_init(void);
void goblin_left_ear_act(void);

// Declarations from config\components\creature_specific\goblin_left_eye.hdr
// Auto-generated header for goblin_left_eye
#include <esp_err.h>

esp_err_t goblin_left_eye_init(void);
void goblin_left_eye_act(void);

// Declarations from config\components\creature_specific\goblin_mouth.hdr
// Auto-generated header for goblin_mouth
#include <esp_err.h>

esp_err_t goblin_mouth_init(void);
void goblin_mouth_act(void);

// Declarations from config\components\creature_specific\goblin_nose.hdr
// Auto-generated header for goblin_nose
#include <esp_err.h>

esp_err_t goblin_nose_init(void);
void goblin_nose_act(void);

// Declarations from config\components\creature_specific\goblin_right_ear.hdr
// Auto-generated header for goblin_right_ear
#include <esp_err.h>

esp_err_t goblin_right_ear_init(void);
void goblin_right_ear_act(void);

// Declarations from config\components\creature_specific\goblin_right_eye.hdr
// Auto-generated header for goblin_right_eye
#include <esp_err.h>

esp_err_t goblin_right_eye_init(void);
void goblin_right_eye_act(void);

// Declarations from config\components\creature_specific\goblin_speaker.hdr
// Auto-generated header for goblin_speaker
#include <esp_err.h>

esp_err_t goblin_speaker_init(void);
void goblin_speaker_act(void);

#endif // GOBLIN_HEAD_COMPONENT_FUNCTIONS_HPP
