#ifndef GOBLIN_HEAD_COMPONENT_FUNCTIONS_HPP
#define GOBLIN_HEAD_COMPONENT_FUNCTIONS_HPP

#include <cstddef>
#include <cstdint>
#include "esp_err.h"

// Auto-generated by tools/generate_tables.py
// Subsystem: goblin_head
// Controller: ESP32_S3_R8N16

// ---------------------------------------------------------------------------
// Function prototypes
// ---------------------------------------------------------------------------
esp_err_t gc9a01_init(void);
void gc9a01_act(void);
esp_err_t generic_spi_display_init(void);
void generic_spi_display_act(void);
esp_err_t goblin_eye_init(void);
void goblin_eye_act(void);
esp_err_t goblin_left_ear_init(void);
void goblin_left_ear_act(void);
esp_err_t goblin_left_eye_init(void);
void goblin_left_eye_act(void);
esp_err_t goblin_mouth_init(void);
void goblin_mouth_act(void);
esp_err_t goblin_nose_init(void);
void goblin_nose_act(void);
esp_err_t goblin_right_ear_init(void);
void goblin_right_ear_act(void);
esp_err_t goblin_right_eye_init(void);
void goblin_right_eye_act(void);
esp_err_t goblin_speaker_init(void);
void goblin_speaker_act(void);
esp_err_t hc_sr04_ultrasonic_distance_sensor_init(void);
void hc_sr04_ultrasonic_distance_sensor_act(void);
esp_err_t hw496_microphone_init(void);
void hw496_microphone_act(void);
esp_err_t i2s_bus_0_init(void);
void i2s_bus_0_act(void);
esp_err_t i2s_driver_init(void);
void i2s_driver_act(void);
esp_err_t ili9341_init(void);
void ili9341_act(void);
esp_err_t servo_sg90_micro_init(void);
void servo_sg90_micro_act(void);
esp_err_t speaker_init(void);
void speaker_act(void);
esp_err_t spi_display_bus_init(void);
void spi_display_bus_act(void);

// Declarations from config\components\hardware\gc9a01.hdr
// gc9a01 component header
// Defines data structures for GC9A01 display

#ifndef GC9A01_HDR
#define GC9A01_HDR

#include <stdint.h>

// This struct acts as a "type bundle" for the gc9a01 hardware.
// It will be used as a template parameter for components that need its properties.
struct gc9a01
{
    // Standardized interface members
    static const int WIDTH = 240;
    static const int HEIGHT = 240;

    // Standardized color channel maximums
    static const int MAX_RED   = 0x1F;
    static const int MAX_GREEN = 0x3F;
    static const int MAX_BLUE  = 0x1F;

    // Standardized nested Pixel type
    struct Pixel
    {
        unsigned int red : 5;
        unsigned int green : 6;
        unsigned int blue : 5;

        // Default constructor
        Pixel() : red(0), green(0), blue(0) {}

        // Copy constructor
        Pixel(const Pixel& other)
        {
            red = other.red;
            green = other.green;
            blue = other.blue;
        }

        // Assignment operator
        Pixel& operator=(const Pixel& other)
        {
            red = other.red;
            green = other.green;
            blue = other.blue;
            return *this;
        }

        // Add two pixels with saturation
        Pixel operator+(const Pixel& other) const
        {
            Pixel result;
            unsigned int sum_r = red + other.red;
            result.red = (sum_r > MAX_RED) ? MAX_RED : sum_r;
            unsigned int sum_g = green + other.green;
            result.green = (sum_g > MAX_GREEN) ? MAX_GREEN : sum_g;
            unsigned int sum_b = blue + other.blue;
            result.blue = (sum_b > MAX_BLUE) ? MAX_BLUE : sum_b;
            return result;
        }
    };
};

#endif // GC9A01_HDR

// Declarations from config\components\hardware\generic_spi_display.hdr
#ifndef GENERIC_SPI_DISPLAY_HDR
#define GENERIC_SPI_DISPLAY_HDR

#include <esp_err.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @brief Initialize generic_spi_display component
 * @return ESP_OK on success, error code otherwise
 */
esp_err_t generic_spi_display_init(void);

/**
 * @brief Execute generic_spi_display component action
 * Called periodically by subsystem dispatcher
 */
void generic_spi_display_act(void);

#ifdef __cplusplus
}
#endif

#endif // GENERIC_SPI_DISPLAY_HDR

// Declarations from config\bots\bot_families\goblins\head\goblin_eye.hdr
// goblin_eye.hdr
#ifndef GOBLIN_EYE_HDR
#define GOBLIN_EYE_HDR

#include "esp_err.h"
#include "config/components/hardware/gc9a01.hdr"  // For Pixel type

// Global variables for spi_display_bus compatibility
// These are set by goblin_eye_act() to provide chunked data interface
extern Pixel* goblin_eye_chunk_buffer;
extern uint16_t goblin_eye_chunk_width;
extern uint16_t goblin_eye_chunk_height;

// Global flag indicating whether child components should initialize hardware
// Set by goblin_eye_init() based on call count (true every 8th call)
extern bool goblin_eye_should_init_hardware;

esp_err_t goblin_eye_init(void);
void goblin_eye_act(void);

#endif // GOBLIN_EYE_HDR

// Declarations from config\bots\bot_families\goblins\head\goblin_left_ear.hdr
// Auto-generated header for goblin_left_ear
#include <esp_err.h>

esp_err_t goblin_left_ear_init(void);
void goblin_left_ear_act(void);

// Declarations from config\bots\bot_families\goblins\head\goblin_left_eye.hdr
// Auto-generated header for goblin_left_eye
#include <esp_err.h>

esp_err_t goblin_left_eye_init(void);
void goblin_left_eye_act(void);

// Declarations from config\bots\bot_families\goblins\head\goblin_mouth.hdr
// Auto-generated header for goblin_mouth
#include <esp_err.h>

esp_err_t goblin_mouth_init(void);
void goblin_mouth_act(void);

// Declarations from config\bots\bot_families\goblins\head\goblin_nose.hdr
// Auto-generated header for goblin_nose
#include <esp_err.h>

esp_err_t goblin_nose_init(void);
void goblin_nose_act(void);

// Declarations from config\bots\bot_families\goblins\head\goblin_right_ear.hdr
// Auto-generated header for goblin_right_ear
#include <esp_err.h>

esp_err_t goblin_right_ear_init(void);
void goblin_right_ear_act(void);

// Declarations from config\bots\bot_families\goblins\head\goblin_right_eye.hdr
// Auto-generated header for goblin_right_eye
#include <esp_err.h>

esp_err_t goblin_right_eye_init(void);
void goblin_right_eye_act(void);

// Declarations from config\bots\bot_families\goblins\head\goblin_speaker.hdr
// Auto-generated header for goblin_speaker
#include <esp_err.h>

esp_err_t goblin_speaker_init(void);
void goblin_speaker_act(void);

// Declarations from config\components\hardware\hc_sr04_sensor.hdr
#ifndef HC_SR04_SENSOR_HDR
#define HC_SR04_SENSOR_HDR

#include <esp_err.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @brief Initialize hc_sr04_sensor component
 * @return ESP_OK on success, error code otherwise
 */
esp_err_t hc_sr04_sensor_init(void);

/**
 * @brief Execute hc_sr04_sensor component action
 * Called periodically by subsystem dispatcher
 */
void hc_sr04_sensor_act(void);

#ifdef __cplusplus
}
#endif

#endif // HC_SR04_SENSOR_HDR

// Declarations from config\components\hardware\hw496_microphone.hdr
// HW-496 MEMS Microphone Component Header
// Uses generic microphone driver with HW496-specific configuration

#ifndef hw496_microphone_H
#define hw496_microphone_H

#include "esp_err.h"

// Test declaration
extern int test_hw496_variable;

// Function declarations for dispatch table
esp_err_t hw496_microphone_init(void);
void hw496_microphone_act(void);

#endif // hw496_microphone_H

// Declarations from config\components\interfaces\i2s_bus.hdr
#ifndef I2S_BUS_HDR
#define I2S_BUS_HDR

#include <esp_err.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @brief Initialize i2s_bus component
 * @return ESP_OK on success, error code otherwise
 */
esp_err_t i2s_bus_init(void);

/**
 * @brief Execute i2s_bus component action
 * Called periodically by subsystem dispatcher
 */
void i2s_bus_act(void);

#ifdef __cplusplus
}
#endif

#endif // I2S_BUS_HDR

// Declarations from config\components\drivers\i2s_driver.hdr
#ifndef I2S_DRIVER_HDR
#define I2S_DRIVER_HDR

#include <esp_err.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @brief Initialize i2s_driver component
 * @return ESP_OK on success, error code otherwise
 */
esp_err_t i2s_driver_init(void);

/**
 * @brief Execute i2s_driver component action
 * Called periodically by subsystem dispatcher
 */
void i2s_driver_act(void);

#ifdef __cplusplus
}
#endif

#endif // I2S_DRIVER_HDR

// Declarations from config\components\hardware\ili9341.hdr
#ifndef ILI9341_HDR
#define ILI9341_HDR

#include <stdint.h>

// This struct acts as a "type bundle" for the ili9341 hardware.
// It will be used as a template parameter for components that need its properties.
struct ili9341
{
    // Standardized interface members from ili9341.json
    static const int WIDTH = 480;
    static const int HEIGHT = 320;

    // Standardized color channel maximums from "bits_per_pixel": 18
    static const int MAX_RED   = 0x3F; // 6 bits
    static const int MAX_GREEN = 0x3F; // 6 bits
    static const int MAX_BLUE  = 0x3F; // 6 bits

    // Standardized nested Pixel type for RGB666
    struct Pixel
    {
        unsigned int red : 6;
        unsigned int green : 6;
        unsigned int blue : 6;

        // Default constructor
        Pixel() : red(0), green(0), blue(0) {}

        // Copy constructor
        Pixel(const Pixel& other)
        {
            red = other.red;
            green = other.green;
            blue = other.blue;
        }

        // Assignment operator
        Pixel& operator=(const Pixel& other)
        {
            red = other.red;
            green = other.green;
            blue = other.blue;
            return *this;
        }

        // Add two pixels with saturation
        Pixel operator+(const Pixel& other) const
        {
            Pixel result;
            unsigned int sum_r = red + other.red;
            result.red = (sum_r > MAX_RED) ? MAX_RED : sum_r;
            unsigned int sum_g = green + other.green;
            result.green = (sum_g > MAX_GREEN) ? MAX_GREEN : sum_g;
            unsigned int sum_b = blue + other.blue;
            result.blue = (sum_b > MAX_BLUE) ? MAX_BLUE : sum_b;
            return result;
        }
    };
};

#endif // ILI9341_HDR

// Declarations from config\components\hardware\servo_sg90_micro.hdr
// Auto-generated header for servo_sg90_micro
#include <esp_err.h>

esp_err_t servo_sg90_micro_init(void);
void servo_sg90_micro_act(void);

// Declarations from config\components\hardware\speaker.hdr
#ifndef SPEAKER_HDR
#define SPEAKER_HDR

#include <esp_err.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @brief Initialize speaker component
 * @return ESP_OK on success, error code otherwise
 */
esp_err_t speaker_init(void);

/**
 * @brief Execute speaker component action
 * Called periodically by subsystem dispatcher
 */
void speaker_act(void);

#ifdef __cplusplus
}
#endif

#endif // SPEAKER_HDR

// Declarations from config\components\interfaces\spi_display_bus.hdr
// SPI display bus component header
// Exposes current SPI pin assignment for display devices

#ifndef SPI_DISPLAY_BUS_H
#define SPI_DISPLAY_BUS_H

#include "esp_err.h"
#include "driver/spi_master.h"
#include <stdio.h>

struct spi_display_pinset_t {
    spi_display_pinset_t()
        : mosi(-1), clk(-1), cs(-1), dc(-1), bl(-1), rst(-1), handle(nullptr) {}

    int mosi;
    int clk;
    int cs;
    int dc;
    int bl;
    int rst;
    spi_device_handle_t handle;

    void print() {
        printf("SPI_DISPLAY bus: mosi=%d, sclk=%d, cs=%d, dc=%d\n", mosi, clk, cs, dc);
    }
};

extern spi_display_pinset_t cur_spi_display_pin;

esp_err_t spi_display_bus_init(void);
void spi_display_bus_act(void);

#endif // SPI_DISPLAY_BUS_H

#endif // GOBLIN_HEAD_COMPONENT_FUNCTIONS_HPP
