#ifndef GOBLIN_TORSO_COMPONENT_FUNCTIONS_HPP
#define GOBLIN_TORSO_COMPONENT_FUNCTIONS_HPP

#include <cstddef>
#include <cstdint>
#include "esp_err.h"

// Auto-generated by tools/generate_tables.py
// Subsystem: goblin_torso
// Controller: ESP32_S3_DEVKITC_1

// ---------------------------------------------------------------------------
// Function prototypes
// ---------------------------------------------------------------------------

#endif // GOBLIN_TORSO_COMPONENT_FUNCTIONS_HPP
