#ifndef TEST_HEAD_COMPONENT_FUNCTIONS_HPP
#define TEST_HEAD_COMPONENT_FUNCTIONS_HPP

#include <cstddef>
#include <cstdint>
#include "esp_err.h"

// Auto-generated by tools/generate_tables.py
// Subsystem: test_head
// Controller: ESP32_S3_DEVKITC_1

// ---------------------------------------------------------------------------
// Function prototypes
// ---------------------------------------------------------------------------
esp_err_t goblin_left_eye_init(void);
void goblin_left_eye_act(void);

// Declarations from config\bots\bot_families\goblins\head\goblin_left_eye.hdr
// Auto-generated header for goblin_left_eye
#include <esp_err.h>

esp_err_t goblin_left_eye_init(void);
void goblin_left_eye_act(void);

#endif // TEST_HEAD_COMPONENT_FUNCTIONS_HPP
